version: 0.2
phases:
 install:
  runtime-versions:
    python: 3.7
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "arn:aws:s3:::jaredwomack.com>"
 post_build:
   commands:
     - echo "post_build step"